### PR TITLE
connect: Try to re-connect to proxy

### LINKED ISSUE #53: Reconnect if proxy died
Shim should try to reconnect to the proxy if connection was dropped (e.g. due to proxy is crashed).

### PR DESCRIPTION
**Pull request by dvoytik**
Try to re-connect to proxy if connection is lost (e.g. proxy died)
with RECONNECT_TIMEOUT_S timeout.

This patch is needed to implement high availability of cc-proxy.

Fixes #53.

Signed-off-by: Dmitry Voytik <dmitry.voytik@huawei.com>

### CODE REVIEW

**Comment by amshinde** [comment]
While we try to reconnect to proxy on errors while reading from proxy socket, I think we should do the same for failures to write to the proxy socket.

While this is a good start for ensuring high availability, I would like to mention that we need to keep track of messages for which the shim has not received any acknowledgement from the proxy and attempt to resend them. Right now the shim does not keep track of the responses received from proxy for the messages that it sends. I will open a separate issue for that so that it can be tackled in a separate PR.

File: src/shim.c [hunk 1]
```diff
@@ -703,6 +704,9 @@ handle_proxy_message(struct cc_shim *shim)
 
 	fr = read_frame(shim);
 	if ( !fr) {
+		if (! reconnect_to_proxy(shim)) {
```
Comment (sboeuf) [inline src/shim.c]: You're making lots of assumption by calling this after you got a `fr == NULL`. Indeed, looking at `read_frame()` function, there are several reasons why we could get an error, and they are not all related to the proxy disconnection.

**Review by sboeuf — CHANGES_REQUESTED** [review]

File: src/shim.c (hunk 1 above)
Comment (dvoytik) [inline src/shim.c]: @sboeuf, thanks for the review.

Okay. Re-connection when header length or header version is wrong doesn't make much sense. If I change for these cases instead of returning false to abort()? Would it make sense for you?

Comment (dvoytik) [reply src/shim.c]: @sboeuf, thanks for the review.

Okay. Re-connection when header length or header version is wrong doesn't make much sense. If I change for these cases instead of returning false to abort()? Would it make sense for you?

Comment (sboeuf) [reply src/shim.c]: If I understand you well, you want to change the `return false` with `abort()` in case you get header length or header version which is wrong ? Because you consider those cases like real issues and we should just terminate the shim, right ?

File: src/shim.c [hunk 2]
```diff
@@ -954,6 +958,52 @@ connect_to_proxy(struct cc_shim *shim)
...
+	if (! connect_to_proxy(shim)) {
+		goto try_again;
+	}
+
+	shim_debug("Sending connect command\n");
+	if (! send_connect_command(shim)) {
+		shim_error("Could not send connect command to proxy\n");
+		goto try_again;
+	}
+	add_pollfd(poll_fds, PROXY_SOCK_INDEX, shim->proxy_sock_fd,
```
Comment (jodh-intel) [inline src/shim.c]: Could you add a comment explaining why this is being called again for `PROXY_SOCK_INDEX`.

File: src/shim.c [hunk 3]
```diff
@@ -954,6 +958,52 @@ connect_to_proxy(struct cc_shim *shim)
...
+ * \param shim \ref cc_shim
+ *
+ * \return true on success, false on failure
+ */
+bool reconnect_to_proxy(struct cc_shim *shim)
+{
+	// How many seconds shim tries to reconnect to proxy
+	const int RECONNECT_TIMEOUT_S = 10;
+	// Period between each attempt in milliseconds
+	const int RECONNECT_POLL_MS = 333;
```
Comment (jodh-intel) [inline src/shim.c]: It might be useful if these two variables could be specified as getopt options, defaulting to `#define`'d values you're using here (as that would allow the defaults to be modified at build time and runtime).

File: src/shim.c [hunk 4]
```diff
@@ -954,6 +958,52 @@ connect_to_proxy(struct cc_shim *shim)
...
+
+	shim_warning("Reconnecting to proxy\n");
```
Comment (jodh-intel) [inline src/shim.c]: Could you reference `RECONNECT_TIMEOUT_S` in this message so it is clear from the log how long the shim will wait before giving up. I appreciate that you are logging that on error but our "rule of thumb" is: "if the code is going to sleep / block, always add a log call before that action in case 'the impossible' happens" :smile:

File: src/shim.c (hunk 3 above)
Comment (dvoytik) [reply src/shim.c]: Thanks for the review. Makes sense. Will redo the patch.

File: src/shim.c (hunk 4 above)
Comment (dvoytik) [reply src/shim.c]: Got it. Will rework.

File: src/shim.c (hunk 2 above)
Comment (dvoytik) [reply src/shim.c]: Okay. Will add a comment here. Thanks.

File: src/shim.c (hunk 1 above)
Comment (dvoytik) [reply src/shim.c]: Sorry for the delayed response.

~~So read_frame() can return NULL in case when read_wire_data() fails --> we re-connect.
Also read_frame() return NULL in cases:~~
~~shim == NULL or shim->proxy_sock_fd < 0
fr->header.header_len < MIN_HEADER_WORD_SIZE
 fr->header.version != PROXY_VERSION~~
~~My proposition is to handle these cases the same as failures with allocation --> calling abort(). Doing this way will make read_frame() return NULL only in cases when read_wire_date() failed.~~

UPDATE:
Maybe it's not the best idea to address this problem as part of this PR. For simplicity I reworked the patch to handle only the case when recv() returns 0 ("a stream socket peer has performed an orderly shutdown").

**Comment by dvoytik** [comment]
@sboeuf, I've updated the patch. Could you please review it. Thanks.

**Comment by sboeuf** [comment]
@dvoytik sure, I'll do that tomorrow.

File: src/shim.c [hunk 5]
```diff
@@ -37,12 +37,23 @@
...
 #include "shim.h"
 
+// How many seconds shim tries to reconnect to proxy before it exits
+#ifndef RECONNECT_TIMEOUT_S
+#define RECONNECT_TIMEOUT_S 10
+#endif
+
+// Period between attempts to reconnect to proxy in milliseconds
+#ifndef RECONNECT_POLL_MS
+#define RECONNECT_POLL_MS 333
```
Comment (sboeuf) [inline src/shim.c]: Where does this value come from ? I think we should go with something more simple: `100`, `200`, `300`, ...

File: src/shim.c [hunk 6]
```diff
@@ -954,6 +966,51 @@ connect_to_proxy(struct cc_shim *shim)
 	return false;
 }
 
+inline void sleep_ms(int ms)
+{
+	struct timespec ts = { 0, ms * 1000000L };
```
Comment (sboeuf) [inline src/shim.c]: Might worth changing `1000000L` with `1e6` for more readability.

File: src/shim.c [hunk 7]
```diff
@@ -954,6 +966,51 @@ connect_to_proxy(struct cc_shim *shim)
...
+ *
+ * \return true on success, false on failure
+ */
+bool reconnect_to_proxy(struct cc_shim *shim)
+{
+	shim_warning("Reconnecting to cc-proxy (timeout %d s)\n",
+			shim->timeout);
+	int time = 0;
+
+try_again:
```
Comment (sboeuf) [inline src/shim.c]: Better to avoid using `goto` when possible for more clarity in the code. Use a loop instead:
```c
do {
   ...
} while ()`
```

File: src/shim.c [hunk 8]
```diff
@@ -971,6 +1028,7 @@ print_usage(void) {
         printf("  -c,  --container-id   Container id\n");
         printf("  -d,  --debug          Enable debug output\n");
         printf("  -t,  --token          Connection token passed by cc-proxy\n");
+        printf("  -r,  --rtimeout       Reconnection timeout to cc-proxy in seconds\n");
```
Comment (sboeuf) [inline src/shim.c]: About the long option name, I think you can go with something longer like `reconnect-timeout`

File: src/shim.c [hunk 9]
```diff
@@ -954,6 +966,51 @@ connect_to_proxy(struct cc_shim *shim)
...
+bool reconnect_to_proxy(struct cc_shim *shim)
+{
+	shim_warning("Reconnecting to cc-proxy (timeout %d s)\n",
+			shim->timeout);
+	int time = 0;
+
+try_again:
+	sleep_ms(RECONNECT_POLL_MS);
+	time += RECONNECT_POLL_MS;
+	if (time >= shim->timeout * 1000) {
```
Comment (sboeuf) [inline src/shim.c]: `1e3` instead of `1000` sounds  clearer to me.

File: src/shim.c [hunk 10]
```diff
@@ -983,6 +1041,7 @@ main(int argc, char **argv)
 		.container_id   =  NULL,
 		.proxy_sock_fd  = -1,
 		.token          =  NULL,
+		.timeout = RECONNECT_TIMEOUT_S,
```
Comment (sboeuf) [inline src/shim.c]: Please align this with other assignments.

**Review by sboeuf — COMMENTED** [review]
A few comments, but the PR looks globally good to me.

File: src/shim.c (hunk 5 above)
Comment (dvoytik) [reply src/shim.c]: I'll set it to 100.

Comment (sboeuf) [reply src/shim.c]: Sounds good to me.

File: src/shim.c (hunk 6 above)
Comment (dvoytik) [reply src/shim.c]: gcc 6.4.1 complains, it seems `1e6` is a double literal. I'll replace it with:
```c
struct timespec ts = { 0, ms * 1000 * 1000 };
```

Comment (sboeuf) [reply src/shim.c]: Oh okay, then that's fine, don't change it.

File: src/shim.c (hunk 8 above)
Comment (dvoytik) [reply src/shim.c]: Will do.

File: src/shim.c (hunk 10 above)
Comment (dvoytik) [reply src/shim.c]: Will do.

File: src/shim.c (hunk 7 above)
Comment (dvoytik) [reply src/shim.c]: Ok. I'll rework this piece.

File: src/shim.c (hunk 9 above)
Comment (dvoytik) [reply src/shim.c]: Interesting. For me it's completely opposite :) Nevertheless, I'm not sure it's a good idea to mix double/float literals with integer variables.

File: src/shim.c [hunk 11]
```diff
@@ -954,6 +966,54 @@ connect_to_proxy(struct cc_shim *shim)
...
+			return false;
+		}
+
+		close(shim->proxy_sock_fd);
+		if (! connect_to_proxy(shim)) {
+			continue;
+		}
+
+		shim_debug("Sending connect command\n");
+		if (! send_connect_command(shim)) {
```
Comment (sboeuf) [inline src/shim.c]: Since that's the second place in the code where we use both `connect_to_proxy()` with `send_connect_command()` right after (which is logical), I think we could factorize this through a new function.

File: src/shim.c [hunk 12]
```diff
@@ -971,6 +1031,7 @@ print_usage(void) {
         printf("  -c,  --container-id   Container id\n");
         printf("  -d,  --debug          Enable debug output\n");
         printf("  -t,  --token          Connection token passed by cc-proxy\n");
+        printf("  -r,  --reconnect-timeout Reconnection timeout to cc-proxy in seconds\n");
```
Comment (sboeuf) [inline src/shim.c]: Please align this with the rest of the output.

**Review by sboeuf — COMMENTED** [review]
Two tiny comments.
@jodh-intel @amshinde please take a look.

File: src/shim.c (hunk 11 above)
Comment (dvoytik) [reply src/shim.c]: Okay.

File: src/shim.c (hunk 12 above)
Comment (dvoytik) [reply src/shim.c]: Okay.

File: src/shim.c (hunk 11 above)
Comment (sboeuf) [reply src/shim.c]: @dvoytik you have updated the PR, but I don't think you addressed this comment. Am I missing something ?

**Comment by jodh-intel** [comment]
There are a couple of minor issues:

- I'd add the new option in alphabetical order everywhere in the code.
- Lots of strings hard-coding `cc-proxy` (I'd consider `#define`'ing it to avoid the duplications and make maintenance easier).

But these are nits, so:

lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/54/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim)

**Comment by jodh-intel** [comment]
@amshinde - could you re-review?

File: src/shim.c (hunk 11 above)
Comment (sboeuf) [reply src/shim.c]: @dvoytik ping ?

**Comment by dvoytik** [comment]
@jodh-intel, sure, no problem. I've updated the PR according to your comments. Thanks.

**Comment by sboeuf** [comment]
@dvoytik in case you missed that in the old comments, you've missed one comment I left two weeks ago:
> Since that's the second place in the code where we use both `connect_to_proxy()` with `send_connect_command()` right after (which is logical), I think we could factorize this through a new function.

Does that make sense ?

**Comment by dvoytik** [comment]
@sboeuf, sorry, indeed I missed that comment. Thanks for reminding. I've updated the PR.

**Comment by jodh-intel** [comment]
Hi @dvoytik - are you still planning to work on this?

**Comment by dvoytik** [comment]
@jodh-intel, this PR was ready to merge one month ago in my opinion. I've rebased it again on the latest master. If all tests pass then it should be merged. This PR is needed by https://github.com/clearcontainers/proxy/pull/107

**Comment by grahamwhaley** [comment]
@sboeuf pls re-review - we'll need your status ack :-)

**Review by sboeuf — APPROVED** [review]

**Comment by sboeuf** [comment]
Yes this is fine. Let's wait for the CI on this PR and we can merge it.
LGTM

**Comment by jodh-intel** [comment]
This still needs an ack from a project approver. @sameo, @grahamwhaley, @amshinde - could you take a look?

**Comment by jodh-intel** [comment]
pingety-ping! :smile:

File: src/shim.c [hunk 13]
```diff
@@ -955,6 +968,71 @@ connect_to_proxy(struct cc_shim *shim)
 }
 
 /*
```
Comment (grahamwhaley) [inline src/shim.c]: nitpick: @jodh-intel do these need to be `\*!` comment starts in order to get the marked up comment notionally processed?

**Review by grahamwhaley — COMMENTED** [review]
lgtm
I'd like to hear from @amshinde though for final ack, as primary original author/owner of the proxy iirc

**Comment by grahamwhaley** [comment]
nice work btw @dvoytik :-)

File: src/shim.c (hunk 13 above)
Comment (jodh-intel) [reply src/shim.c]: Yep - good catch.

Aside: I just ran doxygen and found that there are a couple of errors that need correcting for `master` too [ #82]).

**Comment by dvoytik** [comment]
@grahamwhaley, thank you! :)

**Comment by jodh-intel** [comment]
Hi @amshinde - please can you review?

**Comment by jodh-intel** [comment]
@amshinde - I've tested this PR in combination with https://github.com/clearcontainers/proxy/pull/107 and it works a treat! ;-)

**Comment by amshinde** [comment]
@jodh-intel thanks!
lgtm


[Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/54/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim) [Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/54/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim)
